#!/usr/bin/env python
r"""Generate the ``tabular`` body of ``tab:prices`` from its committed artifact.

``tab:prices`` (in ``paper/sections/07_stress.tex``, \cref{sec:wagecurve}) reports
the price-pass-through probe of brief 21: the sign frontier $\sigstar(\eta)$ at
$c_0 = 1.0$ measured with the numeraire held at one (``prices off``, the canonical
model) against the normal-cost pass-through $P_t = w_t/\bar w$ (``prices on``).
It is the empirical spine of the H2 bracket the paper now states: at zero
pass-through wage flexibility does not auto-correct unemployment, at complete
instantaneous pass-through it does, and neither convention is anchored.

Following brief 20's rule -- every table of MEASURED numbers printed in the paper
has a committed generator, so the digits are an output of a script and never
re-typed -- this script emits exactly the rows between ``\midrule`` and
``\bottomrule`` of ``tab:prices``.  It is modelled on ``make_tab_sobol.py``:

  * reads ``results/ces_b21_sigma_star_eta.csv``, ``c0 == 1.0``;
  * one row per $(\eta, \text{prices})$ in printed order, EXCEPT $\eta = 0$, where
    ``prices on`` is byte-identical to ``prices off`` by construction ($w = \bar w$
    so $P \equiv 1$).  The script ASSERTS that identity against the artifact and
    emits a single merged ``off $\equiv$ on`` row -- so the table cannot silently
    print two rows that a later re-run might let drift apart;
  * columns $\eta$, pass-through, $\sigstar$, 95\% CI $[\text{ci\_lo}, \text{ci\_hi}]$,
    and the crossing count ``#cross`` (``n_crossings``) -- the qualifier the
    off control carries (two crossings at $\eta \ge 0.10$) and that
    \cref{tab:wagecurve} drops;
  * rounds the three real-valued columns ONCE, ``decimal.ROUND_HALF_UP``, to three
    decimals (a double rounding is exactly the §5 defect this closes); ``#cross``
    is an integer and printed as one;
  * the $\eta$ label is printed on the first row of each pass-through pair and left
    blank on the ``on`` row, matching the grouped layout of the paper's tables.

Output is printed to stdout: exactly the seven body rows.  The paper carries them
INLINE, between ``\midrule`` and ``\bottomrule``; the ``\midrule`` line itself is
tagged ``% generated by scripts/make_tab_prices.py -- do not hand-edit`` so the
block is marked WITHOUT adding a source line (a standalone comment line would
shift every downstream line number and needlessly churn the rounding-sweep
artifact).  The inline form is chosen over ``\input{generated/...}`` deliberately,
for the same reason as ``tab:sobol``: this brief must not risk the CI build for
the elegance of a separate file.  To refresh the table, run this script and
replace the seven rows; the digits are never edited by hand.

This script MEASURES and formats; it changes no digit in any document itself.
"""
from __future__ import annotations

import os
from decimal import Decimal, ROUND_HALF_UP

import pandas as pd

_HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(_HERE, ".."))
ARTIFACT = os.path.join(ROOT, "results", "ces_b21_sigma_star_eta.csv")

DECIMALS = 3
C0 = 1.0
ETAS = [0.0, 0.05, 0.10, 0.15]      # printed order

# Columns of the artifact used, in printed order after the (eta, prices) key.
REAL_COLS = ["sigma_star", "ci_lo", "ci_hi"]   # round-once to DECIMALS
INT_COL = "n_crossings"                          # printed as an integer

ETA_PAD = 8              # width of the eta cell in the source
PRICES_PAD = 18          # width of the pass-through cell
ROW_END = "\\\\"         # LaTeX end-of-row (two backslashes)


def round_half_up(x, d: int = DECIMALS) -> Decimal:
    """Half-up rounding to ``d`` decimals, once, as an explicit Decimal.

    Identical convention to ``make_tab_sobol.py`` / ``sweep_rounding.py`` /
    ``verify_paper.py``: the shortest round-tripping repr of the double, quantised
    HALF-UP -- NOT Python ``round()`` (banker's rounding), and NOT a second
    rounding.
    """
    q = Decimal(1).scaleb(-d)
    return Decimal(str(float(x))).quantize(q, rounding=ROUND_HALF_UP)


def load_rows() -> dict:
    """(prices, eta) -> {col: value} for the c0 == 1.0 rows of the artifact."""
    df = pd.read_csv(ARTIFACT)
    df = df[df["c0"] == C0]
    table = {}
    for _, r in df.iterrows():
        key = (str(r["prices"]), round(float(r["eta"]), 2))
        table[key] = {c: r[c] for c in REAL_COLS + [INT_COL]}
    return table


def _ci(cell) -> str:
    lo = round_half_up(cell["ci_lo"])
    hi = round_half_up(cell["ci_hi"])
    return f"$[{lo},\\,{hi}]$"


def _cells(cell) -> str:
    """The three trailing cells of a row: sigstar, CI, #cross."""
    sigstar = str(round_half_up(cell["sigma_star"]))
    return f"{sigstar} & {_ci(cell)} & {int(round(float(cell[INT_COL])))}"


def _row(eta_label: str, prices_label: str, cell) -> str:
    return (f"{eta_label:<{ETA_PAD}}& {prices_label:<{PRICES_PAD}}& "
            f"{_cells(cell)}{ROW_END}")


def _assert_eta0_identity(off, on) -> None:
    """At eta = 0 the two conventions are identical by construction (P == 1)."""
    for c in REAL_COLS:
        a, b = float(off[c]), float(on[c])
        if abs(a - b) > 1e-9:
            raise SystemExit(
                f"eta=0 off/on differ on {c}: {a!r} vs {b!r}; the merged "
                f"'off == on' row would be a false claim -- refusing to emit")
    if int(off[INT_COL]) != int(on[INT_COL]):
        raise SystemExit("eta=0 off/on differ on n_crossings -- refusing to emit")


def make_body() -> list[str]:
    """The seven ``tabular`` body rows of tab:prices (between midrule/bottomrule)."""
    table = load_rows()

    def get(prices, eta):
        key = (prices, round(eta, 2))
        if key not in table:
            raise SystemExit(f"missing row for prices={prices!r} eta={eta} in {ARTIFACT}")
        return table[key]

    lines = []
    for eta in ETAS:
        off, on = get("off", eta), get("on", eta)
        label = f"${eta:.2f}$"
        if eta == 0.0:
            _assert_eta0_identity(off, on)
            lines.append(_row(label, r"off\,$\equiv$\,on", off))
        else:
            lines.append(_row(label, "off", off))
            lines.append(_row("", "on", on))
    return lines


def main() -> int:
    for line in make_body():
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
