#!/usr/bin/env python
r"""Generate the ``tabular`` body of ``tab:sobol`` from its committed artifact.

The three discrepancies brief 18/19 found in ``tab:sobol`` (Slope column of
``paper/sections/09_sensitivity.tex``) are not calculation errors: they are
TRANSCRIPTION errors, hand-copied from ``ces_b13_sobol_indices.csv`` into LaTeX
with a double rounding (``0.03947 -> 0.0395 -> 0.040`` instead of the round-once
``0.039``).  Correcting the digits by hand would leave the cause -- a table typed
by hand -- in place.  The project rule "every committed CSV has a committed
generator" (instructions §5) is extended here to its obvious corollary:

    every table of MEASURED numbers printed in the paper has a committed
    generator, so the digits are an output of a script and never re-typed.

This script emits exactly the rows between ``\midrule`` and ``\bottomrule`` of
``tab:sobol``:

  * reads ``results/ces_b13_sobol_indices.csv``, ``estimator == "saltelli"``;
  * five rows in the printed order (``$\delta$``, ``$\pi_0$``, ``$c_0$``,
    ``$\lambda$``, ``$\sigma$``), with the same symbol->parameter map declared in
    ``paper_claims.yaml`` (in particular ``$\lambda$`` is ``wealth_effect``, NOT
    ``expectation_gain``);
  * columns Viability ``S1``, Viability ``S_T``, Slope ``S1``, Slope ``S_T``;
  * rounds ONCE, ``decimal.ROUND_HALF_UP``, to three decimals (a double rounding
    is exactly the defect this closes);
  * NO ``\textbf`` emphasis on any cell (brief 27-bis removed all bold from the
    paper, tables included; the generator stopped emitting it so the inline block
    stays byte-identical to this output);
  * negatives in math mode (``$-0.029$``), matching the existing table.

Output is printed to stdout: exactly the five body rows.  The paper carries them
INLINE, between ``\midrule`` and ``\bottomrule``; the ``\midrule`` line itself is
tagged ``% generated by scripts/make_tab_sobol.py -- do not hand-edit`` so the
block is marked WITHOUT adding a source line (a standalone comment line would
shift every downstream line number and needlessly churn the rounding-sweep
artifact).  The inline form is chosen over ``\input{generated/...}`` deliberately:
this brief must not risk the CI build for the elegance of a separate file
(brief 20 §2.1).  To refresh the table, run this script and replace the five
rows; the digits are never edited by hand.

This script MEASURES and formats; it changes no digit in any document itself.
"""
from __future__ import annotations

import os
from decimal import Decimal, ROUND_HALF_UP

import pandas as pd

_HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(_HERE, ".."))
ARTIFACT = os.path.join(ROOT, "results", "ces_b13_sobol_indices.csv")

DECIMALS = 3

# Printed order and symbol->parameter map (identical to paper_claims.yaml).
ROWS = [
    (r"$\delta$",   "delta"),
    (r"$\pi_0$",    "pi0"),
    (r"$c_0$",      "c0"),
    (r"$\lambda$",  "wealth_effect"),
    (r"$\sigma$",   "sigma"),
]

# Column order: (qoi, index) laid out Viability S1/ST then Slope S1/ST.
COLUMNS = [
    ("viable", "S1"),
    ("viable", "ST"),
    ("slope_raw", "S1"),
    ("slope_raw", "ST"),
]

SYMBOL_PAD = 16          # width of the parameter column in the source
ROW_END = "\\\\"         # LaTeX end-of-row (two backslashes)


def round_half_up(x, d: int = DECIMALS) -> Decimal:
    """Half-up rounding to ``d`` decimals, once, as an explicit Decimal.

    Identical convention to ``sweep_rounding.py`` / ``verify_paper.py``: the
    shortest round-tripping repr of the double, quantised HALF-UP -- NOT Python
    ``round()`` (banker's rounding), and NOT a second rounding.
    """
    q = Decimal(1).scaleb(-d)
    return Decimal(str(float(x))).quantize(q, rounding=ROUND_HALF_UP)


def load_indices() -> dict:
    """(parameter, qoi) -> {'S1': float, 'ST': float} for the saltelli rows."""
    df = pd.read_csv(ARTIFACT)
    df = df[df["estimator"] == "saltelli"]
    table = {}
    for _, r in df.iterrows():
        table[(r["parameter"], r["qoi"])] = {"S1": float(r["S1"]), "ST": float(r["ST"])}
    return table


def format_cell(value) -> str:
    s = str(round_half_up(value))
    if s.startswith("-"):
        s = f"${s}$"           # math-mode minus, as in the current table
    return s


def make_body() -> list[str]:
    """The five ``tabular`` body rows of tab:sobol (between midrule/bottomrule)."""
    table = load_indices()
    lines = []
    for symbol, param in ROWS:
        cells = []
        for qoi, idx in COLUMNS:
            key = (param, qoi)
            if key not in table:
                raise SystemExit(f"missing cell for {param!r} qoi={qoi!r} in {ARTIFACT}")
            value = table[key][idx]
            cells.append(format_cell(value))
        lines.append(f"{symbol:<{SYMBOL_PAD}}& " + " & ".join(cells) + ROW_END)
    return lines


def main() -> int:
    for line in make_body():
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
